//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalCommon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessagesTsv {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesTsv() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FestivalCommon.ResourceMessagesTsv", typeof(ResourceMessagesTsv).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 処理を続行すると以下のファイルが上書きされます。
        ///{0}
        ///続行してよろしいですか？.
        /// </summary>
        internal static string A001 {
            get {
                return ResourceManager.GetString("A001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DSTSV出力基準ファイルを置き換えます。
        ///よろしいですか？.
        /// </summary>
        internal static string A002 {
            get {
                return ResourceManager.GetString("A002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to おすすめ曲情報が未取込ですが、TSVを出力しますか？.
        /// </summary>
        internal static string A003 {
            get {
                return ResourceManager.GetString("A003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        internal static string ALERT_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("ALERT_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明なエラーが発生しました。管理者に連絡してください。.
        /// </summary>
        internal static string E000 {
            get {
                return ResourceManager.GetString("E000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象のファイルが見つかりません。.
        /// </summary>
        internal static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力対象のフォルダが見つかりません。.
        /// </summary>
        internal static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同名のファイルが存在します。上書きしてよろしいですか？.
        /// </summary>
        internal static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの出力に失敗しました。.
        /// </summary>
        internal static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力対象のレコードが見つかりません。.
        /// </summary>
        internal static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付の入力フォーマットが不正です。入力例:2008/11/07　→　20081107.
        /// </summary>
        internal static string E006 {
            get {
                return ResourceManager.GetString("E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付の入力フォーマットが不正です。入力例:2008/11/07.
        /// </summary>
        internal static string E007 {
            get {
                return ResourceManager.GetString("E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作に必要な権限がありません。.
        /// </summary>
        internal static string E008 {
            get {
                return ResourceManager.GetString("E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 過去の日付は指定できません。.
        /// </summary>
        internal static string E009 {
            get {
                return ResourceManager.GetString("E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}：{1} が見つかりません。.
        /// </summary>
        internal static string E010 {
            get {
                return ResourceManager.GetString("E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変換バッチの実行に失敗しました。変換バッチログを確認してください。.
        /// </summary>
        internal static string E011 {
            get {
                return ResourceManager.GetString("E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DSサービス発表日を指定してください。.
        /// </summary>
        internal static string E012 {
            get {
                return ResourceManager.GetString("E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 収集リストは、コンテンツとセットで出力してください。.
        /// </summary>
        internal static string E013 {
            get {
                return ResourceManager.GetString("E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェックボックスがすべて未チェック.
        /// </summary>
        internal static string E014 {
            get {
                return ResourceManager.GetString("E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力する連番を指定してください。.
        /// </summary>
        internal static string E015 {
            get {
                return ResourceManager.GetString("E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下記の出力対象のフォルダが見つかりません。
        ///{0}.
        /// </summary>
        internal static string E016 {
            get {
                return ResourceManager.GetString("E016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiiデータ変換＆チェック先フォルダ：{0}が見つかりません。.
        /// </summary>
        internal static string E017 {
            get {
                return ResourceManager.GetString("E017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたパスに変換バッチが見つかりません。.
        /// </summary>
        internal static string E018 {
            get {
                return ResourceManager.GetString("E018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変換バッチの実行に失敗しました。変換バッチログを確認してください。.
        /// </summary>
        internal static string E019 {
            get {
                return ResourceManager.GetString("E019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 楽曲名英数読みは、コンテンツとセットで出力してください。.
        /// </summary>
        internal static string E021 {
            get {
                return ResourceManager.GetString("E021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手名英数読みは、歌手とセットで出力してください。.
        /// </summary>
        internal static string E022 {
            get {
                return ResourceManager.GetString("E022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンテンツランキング用は、コンテンツとセットで出力してください。.
        /// </summary>
        internal static string E023 {
            get {
                return ResourceManager.GetString("E023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手ランキングは、歌手とセットで出力してください。.
        /// </summary>
        internal static string E024 {
            get {
                return ResourceManager.GetString("E024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイアップランキングは、タイアップとセットで出力してください。.
        /// </summary>
        internal static string E025 {
            get {
                return ResourceManager.GetString("E025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの中身が空の可能性があります。
        ///{0}の取込を中止します。.
        /// </summary>
        internal static string E026 {
            get {
                return ResourceManager.GetString("E026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21カラム以上の行があったため取り込めませんでした。
        ///{0} 行目 選曲番号：{1}.
        /// </summary>
        internal static string E027 {
            get {
                return ResourceManager.GetString("E027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間が入力されていません。.
        /// </summary>
        internal static string E028 {
            get {
                return ResourceManager.GetString("E028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間が正しくありません。.
        /// </summary>
        internal static string E029 {
            get {
                return ResourceManager.GetString("E029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} 行目   曲ID：{1} に NULLのカラムがあります。
        ///ランキング取込を中止します。.
        /// </summary>
        internal static string E030 {
            get {
                return ResourceManager.GetString("E030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 行目   曲ID：{1} のカラム数が少ないです。
        ///ランキング取込を中止します。.
        /// </summary>
        internal static string E031 {
            get {
                return ResourceManager.GetString("E031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} 行目   曲ID：{1} のカラム数が多いです。
        ///ランキング取込を中止します。.
        /// </summary>
        internal static string E032 {
            get {
                return ResourceManager.GetString("E032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 行目  SONG_GROUPID：{1} に NULLのカラムがあります。
        ///ランキング取込を中止します。.
        /// </summary>
        internal static string E033 {
            get {
                return ResourceManager.GetString("E033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 行目   SONG_GROUPID：{1} のカラム数が少ないです。
        ///ランキング取込を中止します。.
        /// </summary>
        internal static string E034 {
            get {
                return ResourceManager.GetString("E034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 行目   SONG_GROUPID：{1} のカラム数が多いです。
        ///ランキング取込を中止します。.
        /// </summary>
        internal static string E035 {
            get {
                return ResourceManager.GetString("E035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メッセージコード：E036.
        /// </summary>
        internal static string E036 {
            get {
                return ResourceManager.GetString("E036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E037 {
            get {
                return ResourceManager.GetString("E037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例外が発生しました。
        ///【発生日時】 {0}
        ///【発生箇所】 {1}
        ///【障害内容】 {2}
        ///【備考】エラーログを{3}に出力します。
        ///システム担当者に連絡して下さい。.
        /// </summary>
        internal static string E038 {
            get {
                return ResourceManager.GetString("E038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力対象のデータを選択してから実行してください。.
        /// </summary>
        internal static string E039 {
            get {
                return ResourceManager.GetString("E039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E040 {
            get {
                return ResourceManager.GetString("E040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E041 {
            get {
                return ResourceManager.GetString("E041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E042 {
            get {
                return ResourceManager.GetString("E042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E043 {
            get {
                return ResourceManager.GetString("E043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} サーバー上にある{1} データベースに接続できません。データベースが存在し、サーバーが実行中であることを確認してください。.
        /// </summary>
        internal static string E044 {
            get {
                return ResourceManager.GetString("E044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌手ID変更履歴は、コンテンツと歌手とセットで出力してください。.
        /// </summary>
        internal static string E045 {
            get {
                return ResourceManager.GetString("E045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加曲は、サービス情報とセットで出力してください。.
        /// </summary>
        internal static string E046 {
            get {
                return ResourceManager.GetString("E046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E047 {
            get {
                return ResourceManager.GetString("E047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E048 {
            get {
                return ResourceManager.GetString("E048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E049 {
            get {
                return ResourceManager.GetString("E049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E050 {
            get {
                return ResourceManager.GetString("E050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string E056 {
            get {
                return ResourceManager.GetString("E056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string ERROR_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSV各種：{0} にファイルを出力しました。.
        /// </summary>
        internal static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了しました。.
        /// </summary>
        internal static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to おすすめ曲取込完了.
        /// </summary>
        internal static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【総合ランキング】
        ///{0} 件取り込みました。
        ///{1} 件失敗しました。.
        /// </summary>
        internal static string I004 {
            get {
                return ResourceManager.GetString("I004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【年間ランキング】
        ///{0} 件取り込みました。
        ///{1} 件失敗しました。.
        /// </summary>
        internal static string I005 {
            get {
                return ResourceManager.GetString("I005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作に必要な権限がありません。.
        /// </summary>
        internal static string I006 {
            get {
                return ResourceManager.GetString("I006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string I007 {
            get {
                return ResourceManager.GetString("I007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string I008 {
            get {
                return ResourceManager.GetString("I008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string I009 {
            get {
                return ResourceManager.GetString("I009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string I010 {
            get {
                return ResourceManager.GetString("I010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string INFO_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("INFO_TITLE_MESSAGE", resourceCulture);
            }
        }
    }
}
