//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festival.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("thanhnt")]
        public string CONNECT_Server {
            get {
                return ((string)(this["CONNECT_Server"]));
            }
            set {
                this["CONNECT_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string CONNECT_UserID {
            get {
                return ((string)(this["CONNECT_UserID"]));
            }
            set {
                this["CONNECT_UserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@dmin123")]
        public string CONNECT_Password {
            get {
                return ((string)(this["CONNECT_Password"]));
            }
            set {
                this["CONNECT_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wii")]
        public string CONNECT_DBName {
            get {
                return ((string)(this["CONNECT_DBName"]));
            }
            set {
                this["CONNECT_DBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CONNECT_DDETimeout_CheckConnecting {
            get {
                return ((int)(this["CONNECT_DDETimeout_CheckConnecting"]));
            }
            set {
                this["CONNECT_DDETimeout_CheckConnecting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int CONNECT_DDETimeout {
            get {
                return ((int)(this["CONNECT_DDETimeout"]));
            }
            set {
                this["CONNECT_DDETimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int CONNECT_CommandTimeout {
            get {
                return ((int)(this["CONNECT_CommandTimeout"]));
            }
            set {
                this["CONNECT_CommandTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WiiTmp")]
        public string CONNECT_TMPDBName {
            get {
                return ((string)(this["CONNECT_TMPDBName"]));
            }
            set {
                this["CONNECT_TMPDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\")]
        public string FES_CONTENT_INPUT_入力パス {
            get {
                return ((string)(this["FES_CONTENT_INPUT_入力パス"]));
            }
            set {
                this["FES_CONTENT_INPUT_入力パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"歌手名 NULL;[歌手名] is null;曲名 NULL;[楽曲名] is null;PU_ARTIST_IDが空;[PU_ARTIST_ID] is null;アップ予定日登録;[歌唱可能日] is not null and [アップ予定日] is null  and  [サービス発表日] is null;未アップ曲;[アップ予定日] is not null and [サービス発表日] is null;サービス中楽曲;[サービス発表日] is not null and [取消フラグ] is not null;未配信曲でOrchestraサービス中;[サービス発表日] is null and [Wii_U_サービス発表日] is not null;ナビDB親曲なし;[SONG_GROUP_INTRO_TYPE] is null;削除情報あり;[カラオケ削除情報] is not null")]
        public string FES_CONENT_COMBOX_DATA_登録済み条件_検索条件 {
            get {
                return ((string)(this["FES_CONENT_COMBOX_DATA_登録済み条件_検索条件"]));
            }
            set {
                this["FES_CONENT_COMBOX_DATA_登録済み条件_検索条件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fes収集リスト;楽曲リスト")]
        public string COMBOX_TSV_出力条件 {
            get {
                return ((string)(this["COMBOX_TSV_出力条件"]));
            }
            set {
                this["COMBOX_TSV_出力条件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\x-drv\\K-tai\\digidoco\\upload\\tsv\\festival\\")]
        public string RIBBON_EXPORT_MENU_FES_CONTENT_Fes収集リストパス {
            get {
                return ((string)(this["RIBBON_EXPORT_MENU_FES_CONTENT_Fes収集リストパス"]));
            }
            set {
                this["RIBBON_EXPORT_MENU_FES_CONTENT_Fes収集リストパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("録音可能曲.txt")]
        public string FES_CONTENT_IMPORT_FILE_TXT_録音可能曲リスト取込 {
            get {
                return ((string)(this["FES_CONTENT_IMPORT_FILE_TXT_録音可能曲リスト取込"]));
            }
            set {
                this["FES_CONTENT_IMPORT_FILE_TXT_録音可能曲リスト取込"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更新項目.xls")]
        public string FES_CONTENT_IMPORT_FILE_XSL_更新項目リスト取込 {
            get {
                return ((string)(this["FES_CONTENT_IMPORT_FILE_XSL_更新項目リスト取込"]));
            }
            set {
                this["FES_CONTENT_IMPORT_FILE_XSL_更新項目リスト取込"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\Maprj\\xing\\Fes\\tbl_Fes録音可能リスト.txt")]
        public string FES_CONTENT_SERVER_PATH_録音可能リスト取込配置ファイル {
            get {
                return ((string)(this["FES_CONTENT_SERVER_PATH_録音可能リスト取込配置ファイル"]));
            }
            set {
                this["FES_CONTENT_SERVER_PATH_録音可能リスト取込配置ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string RIBBON_EXPORT_MENU_楽曲リストパス {
            get {
                return ((string)(this["RIBBON_EXPORT_MENU_楽曲リストパス"]));
            }
            set {
                this["RIBBON_EXPORT_MENU_楽曲リストパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\x-drv\\K-tai\\digidoco\\upload\\tsv\\festival\\TSV出力結果.txt")]
        public string FEST_TSV_LOG_PATH_ログファイル {
            get {
                return ((string)(this["FEST_TSV_LOG_PATH_ログファイル"]));
            }
            set {
                this["FEST_TSV_LOG_PATH_ログファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\recommend_song_")]
        public string FES_TSV_RECOMMEND_SONG_おすすめ曲 {
            get {
                return ((string)(this["FES_TSV_RECOMMEND_SONG_おすすめ曲"]));
            }
            set {
                this["FES_TSV_RECOMMEND_SONG_おすすめ曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".tsv")]
        public string TSV_EXTENSION_ファイル拡張子 {
            get {
                return ((string)(this["TSV_EXTENSION_ファイル拡張子"]));
            }
            set {
                this["TSV_EXTENSION_ファイル拡張子"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\x-drv\\K-tai\\digidoco\\upload\\tsv\\")]
        public string FES_EXPORT_CONTENT_SERVER_PATH_出力パス {
            get {
                return ((string)(this["FES_EXPORT_CONTENT_SERVER_PATH_出力パス"]));
            }
            set {
                this["FES_EXPORT_CONTENT_SERVER_PATH_出力パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Work\\")]
        public string FES_EXPORT_LOCAL_FOLDER_WORK_作業フォルダ {
            get {
                return ((string)(this["FES_EXPORT_LOCAL_FOLDER_WORK_作業フォルダ"]));
            }
            set {
                this["FES_EXPORT_LOCAL_FOLDER_WORK_作業フォルダ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Fes\\LogTsv\\ContentsLog.ini")]
        public string FES_EXPORT_CONTENT_INIT_LOG_PATH {
            get {
                return ((string)(this["FES_EXPORT_CONTENT_INIT_LOG_PATH"]));
            }
            set {
                this["FES_EXPORT_CONTENT_INIT_LOG_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_CONTENT_コンテンツ {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_CONTENT_コンテンツ"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_CONTENT_コンテンツ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSコンテンツ_V2")]
        public string FILE_NAME_FES_EXPORT_CONTENT_V2_コンテンツ_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_CONTENT_V2_コンテンツ_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_CONTENT_V2_コンテンツ_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_SERVICE_サービス情報 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SERVICE_サービス情報"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SERVICE_サービス情報"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSサービス情報_V2")]
        public string FILE_NAME_FES_EXPORT_SERVICE_V2_サービス情報_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SERVICE_V2_サービス情報_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SERVICE_V2_サービス情報_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_TIEUP_タイアップ情報 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_TIEUP_タイアップ情報"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_TIEUP_タイアップ情報"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSタイアップ情報_V2")]
        public string FILE_NAME_FES_EXPORT_TIEUP_V2_タイアップ情報_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_TIEUP_V2_タイアップ情報_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_TIEUP_V2_タイアップ情報_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS歌手")]
        public string FILE_NAME_FES_EXPORT_SINGER_歌手 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SINGER_歌手"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SINGER_歌手"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_GENRE_ジャンル情報 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_GENRE_ジャンル情報"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_GENRE_ジャンル情報"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSジャンル情報_V2")]
        public string FILE_NAME_FES_EXPORT_GENRE_V2_ジャンル情報_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_GENRE_V2_ジャンル情報_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_GENRE_V2_ジャンル情報_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_GENRE_LIST_ジャンルリスト {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_GENRE_LIST_ジャンルリスト"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_GENRE_LIST_ジャンルリスト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSジャンルリスト大ジャンル")]
        public string FILE_NAME_FES_EXPORT_GENRE_LARGE_LIST_ジャンルリスト大 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_GENRE_LARGE_LIST_ジャンルリスト大"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_GENRE_LARGE_LIST_ジャンルリスト大"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSジャンルリスト中ジャンル")]
        public string FILE_NAME_FES_EXPORT_GENRE_IN_LIST_ジャンルリスト中 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_GENRE_IN_LIST_ジャンルリスト中"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_GENRE_IN_LIST_ジャンルリスト中"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSジャンル説明文")]
        public string FILE_NAME_FES_EXPORT_GENRE_DESCRIPTION_ジャンル説明文 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_GENRE_DESCRIPTION_ジャンル説明文"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_GENRE_DESCRIPTION_ジャンル説明文"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_SONG_NAME_ENGLISH_NUMBER_楽曲名英数読み {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SONG_NAME_ENGLISH_NUMBER_楽曲名英数読み"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SONG_NAME_ENGLISH_NUMBER_楽曲名英数読み"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS楽曲名英数読み_V2")]
        public string FILE_NAME_FES_EXPORT_SONG_NAME_ENGLISH_NUMBER_V2_楽曲名英数読み_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SONG_NAME_ENGLISH_NUMBER_V2_楽曲名英数読み_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SONG_NAME_ENGLISH_NUMBER_V2_楽曲名英数読み_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS歌手名英数読み")]
        public string FILE_NAME_FES_EXPORT_SINGER_NAME_歌手名英数読み {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SINGER_NAME_歌手名英数読み"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SINGER_NAME_歌手名英数読み"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSおすすめ曲")]
        public string FILE_NAME_FES_EXPORT_RECOMMEND_SONG_おすすめ曲 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_RECOMMEND_SONG_おすすめ曲"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_RECOMMEND_SONG_おすすめ曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS歌いだし")]
        public string FILE_NAME_FES_EXPORT_START_SINGING_歌い出し {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_START_SINGING_歌い出し"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_START_SINGING_歌い出し"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSsong_id_change_history")]
        public string FILE_NAME_FES_EXPORT_SINGER_ID_CHANGE_HISTORY_歌手ID変更履歴 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SINGER_ID_CHANGE_HISTORY_歌手ID変更履歴"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SINGER_ID_CHANGE_HISTORY_歌手ID変更履歴"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_DISC_VERSION_SONG_DISC版収録曲 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_DISC_VERSION_SONG_DISC版収録曲"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_DISC_VERSION_SONG_DISC版収録曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSディスク版収録曲_V2")]
        public string FILE_NAME_FES_EXPORT_DISC_VERSION_SONG_V2_DISC版収録曲_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_DISC_VERSION_SONG_V2_DISC版収録曲_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_DISC_VERSION_SONG_V2_DISC版収録曲_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FScontents_ranking")]
        public string FILE_NAME_FES_EXPORT_CONTENT_RANKING_コンテンツランキング用 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_CONTENT_RANKING_コンテンツランキング用"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_CONTENT_RANKING_コンテンツランキング用"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSsinger_ranking")]
        public string FILE_NAME_FES_EXPORT_SINGER_RANKING_歌手ランキング {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_SINGER_RANKING_歌手ランキング"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_SINGER_RANKING_歌手ランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_TIEUP_RANKING_タイアップランキング {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_TIEUP_RANKING_タイアップランキング"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_TIEUP_RANKING_タイアップランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FStieup_ranking_V2")]
        public string FILE_NAME_FES_EXPORT_TIEUP_RANKING_V2_タイアップランキング_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_TIEUP_RANKING_V2_タイアップランキング_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_TIEUP_RANKING_V2_タイアップランキング_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSyears_ranking")]
        public string FILE_NAME_FES_EXPORT_RANKING_BY_AGE_年代別ランキング {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_RANKING_BY_AGE_年代別ランキング"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_RANKING_BY_AGE_年代別ランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS更新日付")]
        public string FILE_NAME_FES_EXPORT_UPDATE_DATE_更新日付 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_UPDATE_DATE_更新日付"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_UPDATE_DATE_更新日付"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS追加曲")]
        public string FILE_NAME_FES_EXPORT_ADDITION_SONG_追加曲 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_ADDITION_SONG_追加曲"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_ADDITION_SONG_追加曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS個別映像割付情報")]
        public string FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_ALLOCATION_個別映像割付情報 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_ALLOCATION_個別映像割付情報"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_ALLOCATION_個別映像割付情報"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_DIS_RECORDING_個別映像DISC収録情報 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_DIS_RECORDING_個別映像DISC収録情報"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_DIS_RECORDING_個別映像DISC収録情報"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS個別映像DISC収録情報_V2")]
        public string FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_DIS_RECORDING_V2_個別映像DISC収録情報_V2 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_DIS_RECORDING_V2_個別映像DISC収録情報_V2"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_INVIDUAL_VIDEO_DIS_RECORDING_V2_個別映像DISC収録情報_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSパッケージID情報")]
        public string FILE_NAME_FES_EXPORT_PACKAGE_ID_INFO_パッケージID情報 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_PACKAGE_ID_INFO_パッケージID情報"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_PACKAGE_ID_INFO_パッケージID情報"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSディスク追加削除曲")]
        public string FILE_NAME_FES_EXPORT_ADD_REMOVE_DIS_SONG_ディスク追加削除曲 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_ADD_REMOVE_DIS_SONG_ディスク追加削除曲"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_ADD_REMOVE_DIS_SONG_ディスク追加削除曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS個別映像ディスク追加削除情報")]
        public string FILE_NAME_FES_EXPORT_INDIVIDUAL_VIDEO_DISC_ADDITIONAL_DELETION_個別映像ディスク追加削除情報 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_INDIVIDUAL_VIDEO_DISC_ADDITIONAL_DELETION_個別映像ディスク追加削除情報"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_INDIVIDUAL_VIDEO_DISC_ADDITIONAL_DELETION_個別映像ディスク追加削除情報"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS健康王国おすすめ曲")]
        public string FILE_NAME_FES_EXPORT_HEALTHY_KINGDOM_RECOMMENDED_SONG_健康王国おすすめ曲 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_HEALTHY_KINGDOM_RECOMMENDED_SONG_健康王国おすすめ曲"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_HEALTHY_KINGDOM_RECOMMENDED_SONG_健康王国おすすめ曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSチャプター追加削除曲")]
        public string FILE_NAME_FES_EXPORT_ADD_REMOVE_CHAPTER_SONG_チャプター追加削除曲 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_ADD_REMOVE_CHAPTER_SONG_チャプター追加削除曲"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_ADD_REMOVE_CHAPTER_SONG_チャプター追加削除曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSおすすめプログラム曲")]
        public string FILE_NAME_FES_EXPORT_RECOMMENDED_PROGRAM_LIST_おすすめプログラムリスト {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_RECOMMENDED_PROGRAM_LIST_おすすめプログラムリスト"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_RECOMMENDED_PROGRAM_LIST_おすすめプログラムリスト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSおすすめプログラム名")]
        public string FILE_NAME_FES_EXPORT_RECOMMENDED_PROGRAM_おすすめプログラム名 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_RECOMMENDED_PROGRAM_おすすめプログラム名"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_RECOMMENDED_PROGRAM_おすすめプログラム名"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FS収集リスト")]
        public string FILE_NAME_FES_EXPORT_COLLECTION_LIST_収集リスト {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_COLLECTION_LIST_収集リスト"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_COLLECTION_LIST_収集リスト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSランキング集計期間")]
        public string FILE_NAME_FES_EXPORT_RANKING_AGGREGATION_PERIOD_ランキング集計期間 {
            get {
                return ((string)(this["FILE_NAME_FES_EXPORT_RANKING_AGGREGATION_PERIOD_ランキング集計期間"]));
            }
            set {
                this["FILE_NAME_FES_EXPORT_RANKING_AGGREGATION_PERIOD_ランキング集計期間"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public string FES_EXPORT_DATE_TIME_IN_PUT_最新追加フラグ設定基準日数 {
            get {
                return ((string)(this["FES_EXPORT_DATE_TIME_IN_PUT_最新追加フラグ設定基準日数"]));
            }
            set {
                this["FES_EXPORT_DATE_TIME_IN_PUT_最新追加フラグ設定基準日数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string FES_EXPORT_VERSION_NUMBER_V1 {
            get {
                return ((string)(this["FES_EXPORT_VERSION_NUMBER_V1"]));
            }
            set {
                this["FES_EXPORT_VERSION_NUMBER_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string FES_EXPORT_VERSION_NUMBER_V2 {
            get {
                return ((string)(this["FES_EXPORT_VERSION_NUMBER_V2"]));
            }
            set {
                this["FES_EXPORT_VERSION_NUMBER_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_DISC_版収録曲チェックファイルパス_V1 {
            get {
                return ((string)(this["FES_EXPORT_DISC_版収録曲チェックファイルパス_V1"]));
            }
            set {
                this["FES_EXPORT_DISC_版収録曲チェックファイルパス_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\DISC版収録曲チェックファイル_V2.txt")]
        public string FES_EXPORT_DISC_版収録曲チェックファイルパス_V2 {
            get {
                return ((string)(this["FES_EXPORT_DISC_版収録曲チェックファイルパス_V2"]));
            }
            set {
                this["FES_EXPORT_DISC_版収録曲チェックファイルパス_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int FES_EXPORT_ADDITION_SONG_LAST_6_DAYS_MAX_NUMBER_CHECK {
            get {
                return ((int)(this["FES_EXPORT_ADDITION_SONG_LAST_6_DAYS_MAX_NUMBER_CHECK"]));
            }
            set {
                this["FES_EXPORT_ADDITION_SONG_LAST_6_DAYS_MAX_NUMBER_CHECK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string FES_EXPORT_加算日 {
            get {
                return ((string)(this["FES_EXPORT_加算日"]));
            }
            set {
                this["FES_EXPORT_加算日"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\x-drv\\K-tai\\digidoco\\upload\\tsv\\")]
        public string FES_EXPORT_FORLDER_SERVER_出力パス {
            get {
                return ((string)(this["FES_EXPORT_FORLDER_SERVER_出力パス"]));
            }
            set {
                this["FES_EXPORT_FORLDER_SERVER_出力パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\背景映像コードチェックファイル_V2.txt")]
        public string FES_EXPORT_背景映像コードチェックファイルパス_V2 {
            get {
                return ((string)(this["FES_EXPORT_背景映像コードチェックファイルパス_V2"]));
            }
            set {
                this["FES_EXPORT_背景映像コードチェックファイルパス_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_背景映像コードチェックファイルパス_V1 {
            get {
                return ((string)(this["FES_EXPORT_背景映像コードチェックファイルパス_V1"]));
            }
            set {
                this["FES_EXPORT_背景映像コードチェックファイルパス_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Maprj\\Festival\\old\\FSディスク追加削除曲.tsv")]
        public string FES_EXPORT_LOCAL_PATH_前回ディスク追加削除曲TSVパス {
            get {
                return ((string)(this["FES_EXPORT_LOCAL_PATH_前回ディスク追加削除曲TSVパス"]));
            }
            set {
                this["FES_EXPORT_LOCAL_PATH_前回ディスク追加削除曲TSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\xgmmsxdd01\\Maprj\\xing\\Fes\\tbl_Fes前回ディスク追加削除曲.txt")]
        public string FES_EXPORT_SERVER_PATH_ディスク追加削除曲取込ファイル {
            get {
                return ((string)(this["FES_EXPORT_SERVER_PATH_ディスク追加削除曲取込ファイル"]));
            }
            set {
                this["FES_EXPORT_SERVER_PATH_ディスク追加削除曲取込ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_ディスク追加削除曲チェックファイルパス {
            get {
                return ((string)(this["FES_EXPORT_ディスク追加削除曲チェックファイルパス"]));
            }
            set {
                this["FES_EXPORT_ディスク追加削除曲チェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Maprj\\Festival\\old\\FS個別映像ディスク追加削除情報.tsv")]
        public string FES_EXPORT_前回個別映像ディスク追加削除情報TSVパス {
            get {
                return ((string)(this["FES_EXPORT_前回個別映像ディスク追加削除情報TSVパス"]));
            }
            set {
                this["FES_EXPORT_前回個別映像ディスク追加削除情報TSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\xgmmsxdd01\\Maprj\\xing\\Fes\\tbl_Fes前回個別映像ディスク追加削除情報.txt")]
        public string FES_EXPORT_個別映像ディスク追加削除情報取込ファイル {
            get {
                return ((string)(this["FES_EXPORT_個別映像ディスク追加削除情報取込ファイル"]));
            }
            set {
                this["FES_EXPORT_個別映像ディスク追加削除情報取込ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Maprj\\Festival\\チャプター追加削除曲フラグチェックファイル.txt")]
        public string FES_EXPORT_チャプター追加削除曲フラグチェックファイルパス {
            get {
                return ((string)(this["FES_EXPORT_チャプター追加削除曲フラグチェックファイルパス"]));
            }
            set {
                this["FES_EXPORT_チャプター追加削除曲フラグチェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Maprj\\Festival\\old\\FSチャプター追加削除曲.tsv")]
        public string FES_EXPORT_前回チャプター追加削除曲TSVパス {
            get {
                return ((string)(this["FES_EXPORT_前回チャプター追加削除曲TSVパス"]));
            }
            set {
                this["FES_EXPORT_前回チャプター追加削除曲TSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\xgmmsxdd01\\Maprj\\xing\\Fes\\tbl_Fes前回チャプター追加削除曲.txt")]
        public string FES_EXPORT_チャプター追加削除曲取込ファイル {
            get {
                return ((string)(this["FES_EXPORT_チャプター追加削除曲取込ファイル"]));
            }
            set {
                this["FES_EXPORT_チャプター追加削除曲取込ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_チャプター追加削除曲前回チェックファイルパス {
            get {
                return ((string)(this["FES_EXPORT_チャプター追加削除曲前回チェックファイルパス"]));
            }
            set {
                this["FES_EXPORT_チャプター追加削除曲前回チェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\cdn_wjk_total_month_150_")]
        public string IMPORT_RANKING_総合ランキング {
            get {
                return ((string)(this["IMPORT_RANKING_総合ランキング"]));
            }
            set {
                this["IMPORT_RANKING_総合ランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\year_ranking_.txt")]
        public string IMPORT_RANKING_年間ランキング {
            get {
                return ((string)(this["IMPORT_RANKING_年間ランキング"]));
            }
            set {
                this["IMPORT_RANKING_年間ランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\recommend_song_")]
        public string FES_EXPORT_RECOMEND_SONG_LOCAL_PATH_おすすめ曲 {
            get {
                return ((string)(this["FES_EXPORT_RECOMEND_SONG_LOCAL_PATH_おすすめ曲"]));
            }
            set {
                this["FES_EXPORT_RECOMEND_SONG_LOCAL_PATH_おすすめ曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\xgmmsxdd01\\Maprj\\xing\\Fes\\TBL_RecommendSong.txt")]
        public string FES_EXPORT_RECOMEND_SONG_SERVER_PATH_読替おすすめ曲取込配置ファイル {
            get {
                return ((string)(this["FES_EXPORT_RECOMEND_SONG_SERVER_PATH_読替おすすめ曲取込配置ファイル"]));
            }
            set {
                this["FES_EXPORT_RECOMEND_SONG_SERVER_PATH_読替おすすめ曲取込配置ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\old\\FSコンテンツ.tsv")]
        public string FES_EXPORT_歌手変更履歴取得元コンテンツTSVパス {
            get {
                return ((string)(this["FES_EXPORT_歌手変更履歴取得元コンテンツTSVパス"]));
            }
            set {
                this["FES_EXPORT_歌手変更履歴取得元コンテンツTSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\old\\FS歌手.tsv")]
        public string FES_EXPORT_歌手変更履歴取得元歌手TSVパス {
            get {
                return ((string)(this["FES_EXPORT_歌手変更履歴取得元歌手TSVパス"]));
            }
            set {
                this["FES_EXPORT_歌手変更履歴取得元歌手TSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\xgmmsxdd01\\Maprj\\xing\\Fes\\tbl_Fes前回歌手.txt")]
        public string FES_EXPORT_歌手取込配置ファイル {
            get {
                return ((string)(this["FES_EXPORT_歌手取込配置ファイル"]));
            }
            set {
                this["FES_EXPORT_歌手取込配置ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\xgmmsxdd01\\Maprj\\xing\\Fes\\tbl_Fes前回コンテンツ.txt")]
        public string FES_EXPORT_コンテンツ取込配置ファイル {
            get {
                return ((string)(this["FES_EXPORT_コンテンツ取込配置ファイル"]));
            }
            set {
                this["FES_EXPORT_コンテンツ取込配置ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Maprj\\Festival\\おすすめプログラムリストチェックファイル.txt")]
        public string FES_EXPORT_おすすめプログラムリストチェックファイルパス {
            get {
                return ((string)(this["FES_EXPORT_おすすめプログラムリストチェックファイルパス"]));
            }
            set {
                this["FES_EXPORT_おすすめプログラムリストチェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_出力ファイルリスト_V1 {
            get {
                return ((string)(this["FES_EXPORT_出力ファイルリスト_V1"]));
            }
            set {
                this["FES_EXPORT_出力ファイルリスト_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"FSコンテンツ_V2;FSサービス情報_V2;FSタイアップ情報_V2;FS歌手;FSジャンル情報_V2;FSジャンルリスト大ジャンル;FSジャンルリスト中ジャンル;FSジャンル説明文;FS楽曲名英数読み_V2;FS歌手名英数読み;FSおすすめ曲;FS歌いだし;FSディスク版収録曲_V2;FSsong_id_change_history;FScontents_ranking;FSsinger_ranking;FStieup_ranking_V2;FSyears_ranking;FS更新日付;FSランキング集計期間;FS追加曲;FS個別映像割付情報;FS個別映像DISC収録情報_V2;FSパッケージID情報;FS収集リスト;FS健康王国おすすめ曲;FSおすすめプログラム曲;FSおすすめプログラム名")]
        public string FES_EXPORT_出力ファイルリスト_V2 {
            get {
                return ((string)(this["FES_EXPORT_出力ファイルリスト_V2"]));
            }
            set {
                this["FES_EXPORT_出力ファイルリスト_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("festivalv2\\all\\search\\")]
        public string FES_EXPORT_出力パス_V2 {
            get {
                return ((string)(this["FES_EXPORT_出力パス_V2"]));
            }
            set {
                this["FES_EXPORT_出力パス_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSディスク追加削除曲;FS個別映像ディスク追加削除情報;FSチャプター追加削除曲")]
        public string FES_EXPORT_出力対象ファイルリネーム後名称_V2_HDD {
            get {
                return ((string)(this["FES_EXPORT_出力対象ファイルリネーム後名称_V2_HDD"]));
            }
            set {
                this["FES_EXPORT_出力対象ファイルリネーム後名称_V2_HDD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("festivalv2\\all\\hdd\\")]
        public string FES_EXPORT_出力パス_V2_HDD {
            get {
                return ((string)(this["FES_EXPORT_出力パス_V2_HDD"]));
            }
            set {
                this["FES_EXPORT_出力パス_V2_HDD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"FSコンテンツ;FSサービス情報;FSタイアップ情報;FS歌手;FSジャンル情報;FSジャンルリスト大ジャンル;FSジャンルリスト中ジャンル;FSジャンル説明文;FS楽曲名英数読み;FS歌手名英数読み;FSおすすめ曲;FS歌いだし;FSディスク版収録曲;FSsong_id_change_history;FScontents_ranking;FSsinger_ranking;FStieup_ranking;FSyears_ranking;FS更新日付;FSランキング集計期間;FS追加曲;FS個別映像割付情報;FS個別映像DISC収録情報;FSパッケージID情報;FS収集リスト;FS健康王国おすすめ曲;FS健康王国おすすめプログラム曲;FS健康王国おすすめプログラム名")]
        public string FES_EXPORT_出力対象ファイルリネーム後名称_V2 {
            get {
                return ((string)(this["FES_EXPORT_出力対象ファイルリネーム後名称_V2"]));
            }
            set {
                this["FES_EXPORT_出力対象ファイルリネーム後名称_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_出力パス_V1 {
            get {
                return ((string)(this["FES_EXPORT_出力パス_V1"]));
            }
            set {
                this["FES_EXPORT_出力パス_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSディスク追加削除曲;FS個別映像ディスク追加削除情報;FSチャプター追加削除曲")]
        public string FES_EXPORT_出力ファイルリスト_V2_HDD {
            get {
                return ((string)(this["FES_EXPORT_出力ファイルリスト_V2_HDD"]));
            }
            set {
                this["FES_EXPORT_出力ファイルリスト_V2_HDD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_出力対象ファイルリネーム後名称_V1 {
            get {
                return ((string)(this["FES_EXPORT_出力対象ファイルリネーム後名称_V1"]));
            }
            set {
                this["FES_EXPORT_出力対象ファイルリネーム後名称_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("おすすめ曲リスト.txt")]
        public string FES_RECOMMEND_SONG_IMPORT_FILE_おすすめ曲リスト取込 {
            get {
                return ((string)(this["FES_RECOMMEND_SONG_IMPORT_FILE_おすすめ曲リスト取込"]));
            }
            set {
                this["FES_RECOMMEND_SONG_IMPORT_FILE_おすすめ曲リスト取込"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("背景動画コード あり全件;[背景映像コード] is not null")]
        public string FES_VIDEO_ASSIGMENT_SEARCH_検索条件 {
            get {
                return ((string)(this["FES_VIDEO_ASSIGMENT_SEARCH_検索条件"]));
            }
            set {
                this["FES_VIDEO_ASSIGMENT_SEARCH_検索条件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Fes_up\\")]
        public string RIBBON_EXPORT_MENU_FES_VIDEO_ASSIGMENT_映像割付リストパス {
            get {
                return ((string)(this["RIBBON_EXPORT_MENU_FES_VIDEO_ASSIGMENT_映像割付リストパス"]));
            }
            set {
                this["RIBBON_EXPORT_MENU_FES_VIDEO_ASSIGMENT_映像割付リストパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("映像割付リスト")]
        public string FES_VIDEO_ASSIGMENT_EXPORT_DATA_出力条件 {
            get {
                return ((string)(this["FES_VIDEO_ASSIGMENT_EXPORT_DATA_出力条件"]));
            }
            set {
                this["FES_VIDEO_ASSIGMENT_EXPORT_DATA_出力条件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_コンテンツ歌手IDチェックファイルパス_V1 {
            get {
                return ((string)(this["FES_EXPORT_コンテンツ歌手IDチェックファイルパス_V1"]));
            }
            set {
                this["FES_EXPORT_コンテンツ歌手IDチェックファイルパス_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\コンテンツ歌手IDチェックファイル_V2.txt")]
        public string FES_EXPORT_コンテンツ歌手IDチェックファイルパス_V2 {
            get {
                return ((string)(this["FES_EXPORT_コンテンツ歌手IDチェックファイルパス_V2"]));
            }
            set {
                this["FES_EXPORT_コンテンツ歌手IDチェックファイルパス_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\歌いだしチェックファイル.txt")]
        public string FES_EXPORT_歌いだしチェックファイルパス {
            get {
                return ((string)(this["FES_EXPORT_歌いだしチェックファイルパス"]));
            }
            set {
                this["FES_EXPORT_歌いだしチェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_EXPORT_DISC版収録曲チェックファイルパス_V1 {
            get {
                return ((string)(this["FES_EXPORT_DISC版収録曲チェックファイルパス_V1"]));
            }
            set {
                this["FES_EXPORT_DISC版収録曲チェックファイルパス_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\DISC版収録曲チェックファイル_V2.txt")]
        public string FES_EXPORT_DISC版収録曲チェックファイルパス_V2 {
            get {
                return ((string)(this["FES_EXPORT_DISC版収録曲チェックファイルパス_V2"]));
            }
            set {
                this["FES_EXPORT_DISC版収録曲チェックファイルパス_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Maprj\\Festival\\old\\FSディスク追加削除曲.tsv")]
        public string FES_EXPORT_前回ディスク追加削除曲TSVパス {
            get {
                return ((string)(this["FES_EXPORT_前回ディスク追加削除曲TSVパス"]));
            }
            set {
                this["FES_EXPORT_前回ディスク追加削除曲TSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("映像割付リスト.txt")]
        public string FES_VIDEO_ASSIGMENT_IMPORT_EXPORT_FILE_映像割付リスト取込 {
            get {
                return ((string)(this["FES_VIDEO_ASSIGMENT_IMPORT_EXPORT_FILE_映像割付リスト取込"]));
            }
            set {
                this["FES_VIDEO_ASSIGMENT_IMPORT_EXPORT_FILE_映像割付リスト取込"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\js-server\\S-drv\\制作\\発納\\festa映像割付\\")]
        public string FES_VIDEO_ASSIGMENT_DEFAULT_PATH_映像割付リスト取込パス {
            get {
                return ((string)(this["FES_VIDEO_ASSIGMENT_DEFAULT_PATH_映像割付リスト取込パス"]));
            }
            set {
                this["FES_VIDEO_ASSIGMENT_DEFAULT_PATH_映像割付リスト取込パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISCID_V1 あり全件;[FesDISCID] is not null")]
        public string FES_SONG_WITH_DISC_検索条件_V1 {
            get {
                return ((string)(this["FES_SONG_WITH_DISC_検索条件_V1"]));
            }
            set {
                this["FES_SONG_WITH_DISC_検索条件_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISCID_V2 あり全件;[FesDISCID(Ver2)] is not null")]
        public string FES_SONG_WITH_DISC_検索条件_V2 {
            get {
                return ((string)(this["FES_SONG_WITH_DISC_検索条件_V2"]));
            }
            set {
                this["FES_SONG_WITH_DISC_検索条件_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISCID割付リスト.txt")]
        public string FES_SONG_WITH_DISC_FILE_NAME_IMPORT_DISCID割付リスト取込 {
            get {
                return ((string)(this["FES_SONG_WITH_DISC_FILE_NAME_IMPORT_DISCID割付リスト取込"]));
            }
            set {
                this["FES_SONG_WITH_DISC_FILE_NAME_IMPORT_DISCID割付リスト取込"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\xgmmsxdd01\\Maprj\\xing\\Fes\\tbl_FesDISCID割付リスト.txt")]
        public string FES_SONG_WITH_DISC_SERVER_FILE_PATH_IMPORT_DISCID割付リスト取込配置ファイル {
            get {
                return ((string)(this["FES_SONG_WITH_DISC_SERVER_FILE_PATH_IMPORT_DISCID割付リスト取込配置ファイル"]));
            }
            set {
                this["FES_SONG_WITH_DISC_SERVER_FILE_PATH_IMPORT_DISCID割付リスト取込配置ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Festival\\DISCID割付リストチェックファイル.txt")]
        public string FES_SONG_WITH_DISC_IMPORT_LOG_DISCID割付リスト取込チェックファイルパス {
            get {
                return ((string)(this["FES_SONG_WITH_DISC_IMPORT_LOG_DISCID割付リスト取込チェックファイルパス"]));
            }
            set {
                this["FES_SONG_WITH_DISC_IMPORT_LOG_DISCID割付リスト取込チェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_VIDEOS_MANAGERMENT_検索条件 {
            get {
                return ((string)(this["FES_VIDEOS_MANAGERMENT_検索条件"]));
            }
            set {
                this["FES_VIDEOS_MANAGERMENT_検索条件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_SONG_MANAGEMENT_検索条件 {
            get {
                return ((string)(this["FES_SONG_MANAGEMENT_検索条件"]));
            }
            set {
                this["FES_SONG_MANAGEMENT_検索条件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Maprj\\Festival\\個別映像ディスク追加削除情報チェックファイル.txt")]
        public string FES_EXPORT_個別映像ディスク追加削除情報チェックファイルパス {
            get {
                return ((string)(this["FES_EXPORT_個別映像ディスク追加削除情報チェックファイルパス"]));
            }
            set {
                this["FES_EXPORT_個別映像ディスク追加削除情報チェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FES_CHAPTER_MANAGEMENT_検索条件 {
            get {
                return ((string)(this["FES_CHAPTER_MANAGEMENT_検索条件"]));
            }
            set {
                this["FES_CHAPTER_MANAGEMENT_検索条件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("背景ファイルサイズリスト.txt")]
        public string FES_VIDEO_MANAGEMENT_背景ファイルサイズ取込 {
            get {
                return ((string)(this["FES_VIDEO_MANAGEMENT_背景ファイルサイズ取込"]));
            }
            set {
                this["FES_VIDEO_MANAGEMENT_背景ファイルサイズ取込"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISC搭載曲データサイズ.txt")]
        public string FES_SONG_MANAGEMENT_DISC搭載曲データサイズ取込 {
            get {
                return ((string)(this["FES_SONG_MANAGEMENT_DISC搭載曲データサイズ取込"]));
            }
            set {
                this["FES_SONG_MANAGEMENT_DISC搭載曲データサイズ取込"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public int FES_DISK_MANAGEMENT_DISCサイズ {
            get {
                return ((int)(this["FES_DISK_MANAGEMENT_DISCサイズ"]));
            }
            set {
                this["FES_DISK_MANAGEMENT_DISCサイズ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1048576")]
        public int FES_DISK_MANAGEMENT_ファイルサイズの単位 {
            get {
                return ((int)(this["FES_DISK_MANAGEMENT_ファイルサイズの単位"]));
            }
            set {
                this["FES_DISK_MANAGEMENT_ファイルサイズの単位"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\js-server\\S-drv\\制作\\発納\\festa映像割付\\背景映像メンテリスト取込.tsv")]
        public string FES_IMPORT_VIDEO_CODE_LOCK_PATH_背景映像コード {
            get {
                return ((string)(this["FES_IMPORT_VIDEO_CODE_LOCK_PATH_背景映像コード"]));
            }
            set {
                this["FES_IMPORT_VIDEO_CODE_LOCK_PATH_背景映像コード"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\x-drv\\Maprj\\festa\\app\\config\\FesPremiumContentsKbn.txt")]
        public string FES_PEREMIUM_CONTENT_VIDEO_LOCKED_PATH {
            get {
                return ((string)(this["FES_PEREMIUM_CONTENT_VIDEO_LOCKED_PATH"]));
            }
            set {
                this["FES_PEREMIUM_CONTENT_VIDEO_LOCKED_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\js-server\\S-drv\\制作\\発納\\festa映像割付\\更新履歴\\背景映像コード更新履歴.tsv")]
        public string FES_VIDEO_LOCK_HISTORIES_FILE_PATH {
            get {
                return ((string)(this["FES_VIDEO_LOCK_HISTORIES_FILE_PATH"]));
            }
            set {
                this["FES_VIDEO_LOCK_HISTORIES_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\x-drv\\K-tai\\digidoco\\upload\\tsv\\festival\\TSV出力演奏時間Null補正対象.txt")]
        public string FES_EXPORT_LOG_PATH_SERVER_FILE_CONTENT_EMPTY {
            get {
                return ((string)(this["FES_EXPORT_LOG_PATH_SERVER_FILE_CONTENT_EMPTY"]));
            }
            set {
                this["FES_EXPORT_LOG_PATH_SERVER_FILE_CONTENT_EMPTY"] = value;
            }
        }
    }
}
