//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FestivalCommon.Properties.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSGA000.
        /// </summary>
        public static string A000 {
            get {
                return ResourceManager.GetString("A000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;取り込みを中止します。&quot;.
        /// </summary>
        public static string A001 {
            get {
                return ResourceManager.GetString("A001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ご入力必須項目です。.
        /// </summary>
        public static string A002 {
            get {
                return ResourceManager.GetString("A002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 数値をご入力ください。.
        /// </summary>
        public static string A003 {
            get {
                return ResourceManager.GetString("A003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この {0} を削除してもよろしいですか？.
        /// </summary>
        public static string A004 {
            get {
                return ResourceManager.GetString("A004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        public static string ALERT_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("ALERT_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSGE000.
        /// </summary>
        public static string E000 {
            get {
                return ResourceManager.GetString("E000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;処理対象のレコードが見つかりません。&quot;.
        /// </summary>
        public static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;8文字以内で指定してください。&quot;.
        /// </summary>
        public static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;エラーメッセージ:  
        ///&quot;&quot;文字数が384文字を超えています。文字数→&quot;&quot; &amp; エラーメッセージ:  
        ///&quot;文字数が384文字を超えています。文字数→&quot; &amp; {0}  &amp;&lt;改行&gt; 
        ///&quot;最大文字数は、384文字です。&quot;.
        /// </summary>
        public static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;カタカナで指定してください。&quot;.
        /// </summary>
        public static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  
        ///&quot;文字数が256文字を超えています{0}。文字数→&quot;  {1}  &lt;改行&gt; 
        ///&quot;最大文字数は、256文字です。&quot;.
        /// </summary>
        public static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ: {0}が正しくありません。.
        /// </summary>
        public static string E006 {
            get {
                return ResourceManager.GetString("E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;UP予定日が正しくありません。&quot;.
        /// </summary>
        public static string E007 {
            get {
                return ResourceManager.GetString("E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;Orch制作完了日が正しくありません。&quot;.
        /// </summary>
        public static string E008 {
            get {
                return ResourceManager.GetString("E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;登録日時が正しくありません。&quot;.
        /// </summary>
        public static string E009 {
            get {
                return ResourceManager.GetString("E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;停止日が正しくありません。&quot;.
        /// </summary>
        public static string E010 {
            get {
                return ResourceManager.GetString("E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;新譜本扱月が正しくありません。&quot;.
        /// </summary>
        public static string E011 {
            get {
                return ResourceManager.GetString("E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;3文字以内で指定してください。&quot;.
        /// </summary>
        public static string E012 {
            get {
                return ResourceManager.GetString("E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;発売日が正しくありません。&quot;.
        /// </summary>
        public static string E013 {
            get {
                return ResourceManager.GetString("E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;歌唱可能日が正しくありません。&quot;.
        /// </summary>
        public static string E014 {
            get {
                return ResourceManager.GetString("E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ: &quot;カラオケ完パケ期限日が正しくありません。&quot;.
        /// </summary>
        public static string E015 {
            get {
                return ResourceManager.GetString("E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} が正しくありません。.
        /// </summary>
        public static string E016 {
            get {
                return ResourceManager.GetString("E016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  {0} &amp; &quot; 行目 &quot; &amp;  {1} &amp; &quot;のフォーマットが違います。&quot;.
        /// </summary>
        public static string E018 {
            get {
                return ResourceManager.GetString("E018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;数字で指定してください。&quot;.
        /// </summary>
        public static string E019 {
            get {
                return ResourceManager.GetString("E019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  {0} &amp; &quot; 行目 楽曲名邦題が未設定のため、邦題優先フラグを設定することはできません。&quot;.
        /// </summary>
        public static string E020 {
            get {
                return ResourceManager.GetString("E020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fes独自歌手に設定されている歌手IDを指定してください。.
        /// </summary>
        public static string E021 {
            get {
                return ResourceManager.GetString("E021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ: MESSAGE_ERROR_WII_DATE_INCORRECT/n エラーメッセージ:  {0} &amp; &quot; 行目 &quot; &amp;  {1} &amp; &quot;のフォーマットが違います。&quot; &lt;改行&gt;
        ///&quot;入力例：20121101&quot;.
        /// </summary>
        public static string E022 {
            get {
                return ResourceManager.GetString("E022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ:  &quot;半角英数字大文字で指定してください。&quot;.
        /// </summary>
        public static string E023 {
            get {
                return ResourceManager.GetString("E023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 文字で指定してください。.
        /// </summary>
        public static string E024 {
            get {
                return ResourceManager.GetString("E024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSGE025.
        /// </summary>
        public static string E025 {
            get {
                return ResourceManager.GetString("E025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの中身が空の可能性があります。
        ///録音可能曲リストの取込を中止します。.
        /// </summary>
        public static string E026 {
            get {
                return ResourceManager.GetString("E026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カラオケNoのフォーマットが不正な行があったため取り込めませんでした。{0} 行目：{1}.
        /// </summary>
        public static string E027 {
            get {
                return ResourceManager.GetString("E027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取り込むエクセル表のフォーマットが不正です。
        ///正しいフォーマットの列の数：30
        ///以内取り込もうとしてるエクセルの列の数：{0}.
        /// </summary>
        public static string E028 {
            get {
                return ResourceManager.GetString("E028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例外が発生しました。
        ///【発生日時】 {0}
        ///【発生箇所】 {1}
        ///【障害内容】 {2}
        ///【備考】エラーログを{3}に出力します。
        ///システム担当者に連絡して下さい。.
        /// </summary>
        public static string E038 {
            get {
                return ResourceManager.GetString("E038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} サーバー上にある{1} データベースに接続できません。データベースが存在し、サーバーが実行中であることを確認してください。.
        /// </summary>
        public static string E044 {
            get {
                return ResourceManager.GetString("E044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3カラム以外の行があったため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E045 {
            get {
                return ResourceManager.GetString("E045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to おすすめプログラムIDのフォーマットが不正な行があったため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E046 {
            get {
                return ResourceManager.GetString("E046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to おすすめプログラムIDのフォーマットが不正な行があったため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E047 {
            get {
                return ResourceManager.GetString("E047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジドコNoが設定されていないため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E048 {
            get {
                return ResourceManager.GetString("E048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジドコNoのフォーマットが不正な行があったため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E049 {
            get {
                return ResourceManager.GetString("E049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジドコNoのフォーマットが不正な行があったため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E050 {
            get {
                return ResourceManager.GetString("E050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示順が設定されていないため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E051 {
            get {
                return ResourceManager.GetString("E051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示順のフォーマットが不正な行があったため取り込めませんでした。
        ///{0}行目：{1}.
        /// </summary>
        public static string E052 {
            get {
                return ResourceManager.GetString("E052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの中身が空の可能性があります。おすすめ曲リストの取込を中止します。.
        /// </summary>
        public static string E053 {
            get {
                return ResourceManager.GetString("E053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        public static string ERROR_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} このフィールドは編集できません。.
        /// </summary>
        public static string EXPASTE001 {
            get {
                return ResourceManager.GetString("EXPASTE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} このフィールドはデータ型が設定されていません.
        /// </summary>
        public static string EXPASTE002 {
            get {
                return ResourceManager.GetString("EXPASTE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ型が一致しません。.
        /// </summary>
        public static string EXPASTE003 {
            get {
                return ResourceManager.GetString("EXPASTE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データを全件抽出します。時間がかかりますが続行してよろしいですか？.
        /// </summary>
        public static string I000 {
            get {
                return ResourceManager.GetString("I000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全件洗い替えを実施します。元に戻せませんが実行してよろしいですか？.
        /// </summary>
        public static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルが適用されています。続行してよろしいですか？.
        /// </summary>
        public static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} に出力しました。.
        /// </summary>
        public static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新されています。{0}書き込まずに閉じてよろしいですか？.
        /// </summary>
        public static string I004 {
            get {
                return ResourceManager.GetString("I004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新されています。{0} 書き込まずに閉じてよろしいですか？.
        /// </summary>
        public static string I005 {
            get {
                return ResourceManager.GetString("I005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作に必要な権限がありません。.
        /// </summary>
        public static string I006 {
            get {
                return ResourceManager.GetString("I006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録が完了しました。.
        /// </summary>
        public static string I007 {
            get {
                return ResourceManager.GetString("I007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データの更新に失敗しました。
        ///更新予定件数：{0}件
        ///処理件数：{1}件
        ///
        ///デジドコNo:{2}は、更新できませんでした。
        ///楽曲名邦題が未設定のコンテンツに、邦題優先フラグを設定しています。.
        /// </summary>
        public static string I008 {
            get {
                return ResourceManager.GetString("I008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録対象のレコードがありません。.
        /// </summary>
        public static string I009 {
            get {
                return ResourceManager.GetString("I009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この項目は一括入力できません。.
        /// </summary>
        public static string I010 {
            get {
                return ResourceManager.GetString("I010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データを全件抽出します。時間がかかりますが続行してよろしいですか？.
        /// </summary>
        public static string I011 {
            get {
                return ResourceManager.GetString("I011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集中のデータが存在しますが、処理を実行してよろしいですか？.
        /// </summary>
        public static string I012 {
            get {
                return ResourceManager.GetString("I012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        public static string INFO_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("INFO_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在するデジドコNoを指定してください。.
        /// </summary>
        public static string MESSAGE_ERROR_DIGINO_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_DIGINO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジドコNoが設定されていません。.
        /// </summary>
        public static string MESSAGE_ERROR_DIGINO_REQUIRED {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_DIGINO_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象のファイルが見つかりません.
        /// </summary>
        public static string MESSAGE_ERROR_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通番が設定されていません。.
        /// </summary>
        public static string MESSAGE_ERROR_ID_REQUIRED {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作に必要な権限がありません.
        /// </summary>
        public static string MESSAGE_ERROR_NO_AUTHORITY {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_NO_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力対象のレコードが見つかりません.
        /// </summary>
        public static string MESSAGE_ERROR_NO_DATA {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの出力に失敗しました.
        /// </summary>
        public static string MESSAGE_ERROR_OUTPUT_FAILED {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_OUTPUT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明なエラーが発生しました。管理者に連絡してください。.
        /// </summary>
        public static string MESSAGE_ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコード更新.
        /// </summary>
        public static string UPDATE_MESSAGE {
            get {
                return ResourceManager.GetString("UPDATE_MESSAGE", resourceCulture);
            }
        }
    }
}
